<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6KN3HGT8" failures="1" tests="3" name="Test" time="9.619" errors="0" timestamp="2022-03-19T09:16:10 EDT">
  <testcase classname="allureReports.Tests" name="logoPresenceTest" time="0.127"/>
  <testcase classname="allureReports.Tests" name="loginTest" time="1.806">
    <failure type="java.lang.AssertionError" message="expected [Login was unsuccessful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]">
      <![CDATA[java.lang.AssertionError: expected [Login was unsuccessful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]
at allureReports.Tests.loginTest(Tests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="allureReports.Tests" name="registrationTest" time="0.009">
    <skipped/>
  </testcase> <!-- registrationTest -->
</testsuite> <!-- Test -->
